builds:
- goos:
  - freebsd
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archive:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE
    - README.md
    - example.config.json
    - example.students.csv

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"