language: go
sudo: false
go:
  - tip
install:
  - go get -v github.com/golang/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...
script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v ./...
deploy:
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true